name: Playground for echo-inputs-json
on: push
jobs:
  Playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .
        with:
          foo: "FOOFOO"
          baz: "BAZBAZ"

