name: Playground for echo-inputs-json
on: push
jobs:
  playground-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/echo-inputs-json
        with:
          foo: "FOOFOO"

  playground-windows:
    runs-on: windows-latest
    steps:
      - run: printenv
        shell: bash

